"""edits hero_powers, hero and power

Revision ID: b672f7ce9084
Revises: 9559f65420bb
Create Date: 2024-10-13 23:30:53.843508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b672f7ce9084'
down_revision = '9559f65420bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.alter_column('hero_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('power_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_hero_powers_hero_id_heroes', type_='foreignkey')
        batch_op.drop_constraint('fk_hero_powers_power_id_powers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_hero_powers_power_id_powers'), 'powers', ['power_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_hero_powers_hero_id_heroes'), 'heroes', ['hero_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_hero_powers_hero_id_heroes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_hero_powers_power_id_powers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_hero_powers_power_id_powers', 'powers', ['power_id'], ['id'])
        batch_op.create_foreign_key('fk_hero_powers_hero_id_heroes', 'heroes', ['hero_id'], ['id'])
        batch_op.alter_column('power_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hero_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
